### ISSUE TITLE
Feature Request: Rollups and Transformations

### ISSUE THREAD

**Issue by getorca** [zincsearch/zincsearch#153]
**Is your feature request related to a problem? Please describe.**
- With high frequency data timeseries data, it's often beneficial for performance, to roll up the data into avgs, sums etc of a lower frequency time span. 
- With large datasets, summarising the data with an aggregation can sometimes be slow, so it's a benefit to transform the data to it's own index. 

**Describe the solution you'd like**
- a version of elasticsearch rollup jobs in zinc
- a version of transformation jobs in zinc

**Describe alternatives you've considered**
- sticking with elasticsearch or opensearch
- writing rollup and transformation jobs outside of zincsearch. Requires additional complexity, and large code base. 

**Additional context**
Just stumbled on zincsearch from a techcrunch article, and was exploring some of the features vs what I regularly use in ES.

**Comment by prabhatsharma** [comment]
@getorca Thanks for the feature request. I think this is a good feature. I will add it to the backlog. I will also keep it open and let community upvote it.
