### ISSUE TITLE
Better way to search nested arrays

### ISSUE THREAD

**Issue by nnnnt21** [zincsearch/zincsearch#531]
**Is your feature request related to a problem? Please describe.**
Not not a problem per say as I could change my schema

**Describe the solution you'd like**
Some way to search fields in a nested array

**Describe alternatives you've considered**
Changing my schema

**Additional context**
Say my schema is
{
      "name": "bob",
      "nameHistory": [
           {
                 "name": "oldname"
           }
      ]
}

Is there no way to search all documents which have "oldname" in nameHistory, and hopefully support other search types aswell like fuzzy and regex? If not this is my feature request, a better way to search nested arrays.

**Comment by hengfeiyang** [comment]
Yeah, we need think about it. actually, we should support it.
