### ISSUE TITLE
Can't Index Docs where Doc ID has some reserved URL characters. 

### ISSUE THREAD

**Issue by sunny-able** [zincsearch/zincsearch#548]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**What were you trying to achieve?**
Trying to index documents where doc IDs has reserved characters via Elastic's Go APIs. For Example: `id/1234`. With proper escaping, while ES seems to be indexing correctly, Zincsearch seems to be raising 404.

This is using Elasticsearch's Go APIs.

**What action did you take?**
Indexed a document with same ID to both Zinc and Elasticsearch (locally). 
- Elasticsearch indexing and search showed right document id in the index: 'id/1234`. 
- Zincsearch indexing raises `rpc error: code = Unknown desc = [404 Not Found] 404 page not found`
- In both the cases, DocIDs are encoded via `url.QueryEscape(id)` that produces `id%2F1234`. 

**What action/response/output did you expect?**
Zincsearch indexing should go through with similar indexed document.
```
[200 OK] {
    ...
    "hits" : [
      {
        "_index" : "test.index",
        "_id" : "id/1234",
        "_score" : 1.0,
        "_source" : { }
      }
    ]
  }
}
```

**What actually happened?**
Zincsearch indexing raises `rpc error: code = Unknown desc = [404 Not Found] 404 page not found`

**How to reproduce the issue?**
Index document via special characters (`id/1234`) using elastic's go api. 

**What version of ZincSearch are you using?**
v0.3.2

**Anything else that you can tell that will help us diagnose and resolve the issue efficiently?**

**Any attachments/screenshots?**

**Which service(s) is this relate to?**
This could be GUI or API

**Comment by hengfeiyang** [comment]
you should avoid use slash for id. because we use slash to split URL params. 

Let me know if you can change it.

**Comment by sunny-able** [comment]
Thanks for the reply. We could try to consider replacing `/` at our end as a workaround, however would be nice if we could support this especially, since Elastic supports it consistency purposes. For now, it's just gonna be a workaround for us and it won't be able be possible for us to not use `/` at all in our IDs.
