### ISSUE TITLE
Log alerts

### ISSUE THREAD

**Issue by collimarco** [zincsearch/zincsearch#557]
**Is your feature request related to a problem? Please describe.**
Provide a way to get an alert by email when the logs that match a query go above a certain threshold. 
This is useful for example to get notified immediately about internal server errors (HTTP 500), exceptions, etc.

**Describe the solution you'd like**
Provide a way to define an alert ([example](https://docs.logz.io/user-guide/alerts/)):

- query (e.g. status:500)
- threshold (e.g. 2)
- period of time (e.g. 5 minutes)

**Describe alternatives you've considered**
I don't see any alternatives and this is an essential feature (required for us in order to migrate to Zinc).

**Comment by hengfeiyang** [comment]
Yeah, this is a feature in our list, but no plan for it.

**Comment by prabhatsharma** [comment]
This feature is now available in ZincObserve
