### ISSUE TITLE
birthday conv error

### ISSUE THREAD

**Issue by plusgua** [zincsearch/zincsearch#612]
I have a test collection with content in the following format:

```
{....   "f_birthday":"1981-02-20","f_age":"39" ,  .....
```

When I batch import, the server returns the following error

```
curl http://localhost:4080/api/_bulk -i -u admin:admin  --data-binary "@test_50k.ndjson" -v
........
{"error":"field [f_birthday] value [1981-02-20] parse err: time format is [2006-01-02T15:04:05Z07:00] but the value [1981-02-20] parse err: parsing time \"1981-02-20\" as \"2006-01-02T15:04:05Z07:00\": cannot parse \"\" as \"T\""}
* Closing connection 0
```

How can I modify the mapping type or how can I fix the error

thank u .

**Comment by hengfeiyang** [comment]
It looks like you predefined mapping and set `birthday` as a date type.

You should also set date format like this:

```
"birthday": {
  "type": "date",
  "format": "2006-01-02"
}
```

https://docs.zincsearch.com/api/index/update-mapping/#date

**Comment by plusgua** [comment]
1. This is the problem I encountered when using bluk to import in batches, that is to say, set it himself (maybe there are some problems with automatic identification)
2. because I didn't find where to modify the mapping before, so I asked this question.

**Comment by hengfeiyang** [comment]
Yep, maybe there are some problems with automatic identification.

You can create the index with mappings in the UI before ingesting data. at that time, you can set the field format.
