### ISSUE TITLE
Json Array structure not supported

### ISSUE THREAD

**Issue by hhhc** [zincsearch/zincsearch#617]
I am trying to ingest the following json array structure:

`
[
    {
    "name": "Bidhan Chatterjee",
    "email": "bidhan@example.com"
    },
    {
    "name": "Rameshwar Ghosh",
    "email": "datasoftonline@example.com"
    }
]
`

Using curl to ingest a test file for debugging:
`curl 
  -u user:password 
  -XPUT 
  --data "@./storage/json/test.json" 
  http://myip:4080/api/index/_doc`

I get the error: 

{"error":"expected { character for map value"}

When I change the data format to 

`{
    "data" :
    [
        {
        "name": "Bidhan Chatterjee",
        "email": "bidhan@example.com"
        },
        {
        "name": "Rameshwar Ghosh",
        "email": "datasoftonline@example.com"
        }
    ]
}`

it works but according to https://www.w3resource.com/JSON/structures.php and [jsonlint.](https://jsonlint.com/) also the first format is valid.

**What version of ZincSearch are you using?** 
0.3.3

Please advice.

**Comment by hengfeiyang** [comment]
the `_doc` API just accepts an object. 

So your first data is an array and the second is an object.

If you want ingest two doc, you should call the `_doc` twice. or try other API:


https://docs.zincsearch.com/api/document/multi/
https://docs.zincsearch.com/api/document/bulkv2/
