### ISSUE TITLE
zinc does not support nested query

### ISSUE THREAD

**Issue by taoheihei** [zincsearch/zincsearch#621]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**What were you trying to achieve?**
    get a nested query for nested data
**What action did you take?**
  i can not get a doc from [https://docs.zincsearch.com/api/search/search/](https://docs.zincsearch.com/api/search/search/) so i get a doc from  es search dsl from 
[https://www.elastic.co/guide/en/elasticsearch/reference/8.4/query-dsl-nested-query.html](https://www.elastic.co/guide/en/elasticsearch/reference/8.4/query-dsl-nested-query.html) ,but zinc does not supported

**What version of ZincSearch are you using?**
 0.3.3
**Anything else that you can tell that will help us diagnose and resolve the issue efficiently?**
 the nested data mapping like below
`{
  "mappings": {
    "properties": {
      "driver": {
        "type": "nested",
        "properties": {
          "last_name": {
            "type": "text"
          },
          "vehicle": {
            "type": "nested",
            "properties": {
              "make": {
                "type": "text"
              },
              "model": {
                "type": "text"
              }
            }
          }
        }
      }
    }
  }
}`
**Any attachments/screenshots?**
![image](https://user-images.githubusercontent.com/16385417/197740021-cbe0616c-2837-46f4-91f6-f584e140e1bc.png)

**Which service(s) is this relate to?**
 API

**Comment by hengfeiyang** [comment]
Yes, if you can use the query API do a combined query, like this:
```
{
	"query": {
		"bool": {
			"must": [
				{
					"term": {
						"Country": "chn"
					}
				}
			],
			"filter": {
				"term": {
					"Year": "1984"
				}
			}
		}
	}
}
```

**Comment by taoheihei** [comment]
> Yes, if you can use the query API do a combined query, like this:
> 
> ```
> {
> 	"query": {
> 		"bool": {
> 			"must": [
> 				{
> 					"term": {
> 						"Country": "chn"
> 					}
> 				}
> 			],
> 			"filter": {
> 				"term": {
> 					"Year": "1984"
> 				}
> 			}
> 		}
> 	}
> }
> ```
the data just shows below , and   what I want is  doing a nested query in a child array document, just like
  "filter": {
      "match":{
               "vehicle.make": "Power"
       }
  }   
 so is it someway to do it ?
```{
        "last_name" : "McQueen",
        "vehicle" : [
            {
                "make" : "Powell Motors",
                "model" : "Canyonero"
            },
            {
                "make" : "Miller-Meteor",
                "model" : "Ecto-1"
            }
        ]
    }```

**Comment by taoheihei** [comment]
> Yes, if you can use the query API do a combined query, like this:
> 
> ```
> {
> 	"query": {
> 		"bool": {
> 			"must": [
> 				{
> 					"term": {
> 						"Country": "chn"
> 					}
> 				}
> 			],
> 			"filter": {
> 				"term": {
> 					"Year": "1984"
> 				}
> 			}
> 		}
> 	}
> }
> ```
the data just shows below , and   what I want is  doing a nested query in a child array document, just like
  "filter": {
      "match":{
               "vehicle.make": "Power"
       }
  }   
 so is it someway to do it ?
```{
        "last_name" : "McQueen",
        "vehicle" : [
            {
                "make" : "Powell Motors",
                "model" : "Canyonero"
            },
            {
                "make" : "Miller-Meteor",
                "model" : "Ecto-1"
            }
        ]
    }```

**Comment by hengfeiyang** [comment]
It looks like the same issue: https://github.com/zinclabs/zinc/issues/531

For now, we don't support array data. it's a problem.
