### ISSUE TITLE
Log corruption after disk ran full

### ISSUE THREAD

**Issue by DatanoiseTV** [zincsearch/zincsearch#622]
I was running Zinc for one of my projects with 2 million entries in index and already for the 2nd or 3rd time my WAL got corrupted. This results in new documents being inserted not actually being in the index.

```
{"level":"info","index":"XYZ","shard":"1SZHzvVzR1m","minID":2230944,"maxID":2231017,"time":"2022-10-26T10:02:16Z","message":"rollback start"}
{"level":"error","error":"log corrupt","index":"XYZ","shard":"1SZHzvVzR1m","time":"2022-10-26T10:02:16Z","message":"rollback wal.Read()"}

```

**Comment by hengfeiyang** [comment]
Do you clean your full disk? when you restart zinc, what is the log?

**Comment by DatanoiseTV** [comment]
I extended the disk (it is a VM with a ZFS ZVOL) and grown the FS and then rebooted.
Then still log corrupt entries and index doesn't grow when docs get inserted.

**Comment by hengfeiyang** [comment]
Can you send some logs when you restart
