### ISSUE TITLE
Timezones are not supported yet

### ISSUE THREAD

**Issue by aido93** [zincsearch/zincsearch#679]
**What were you trying to achieve?**
I tried to find out which timestamp is valid and why they are differs.

**What action did you take?**
I opened zinc main page and I saw that there are two different times and no timezone environment variable was set.

**What action/response/output did you expect?**
Time should have the same formatting. Also there are should be an environment variable like TZ for setting timezone.

**What actually happened?**
https://imgur.com/a/e5mycnV
Pay attention to times on the screenshot above: 17:15 and 20:15 (TZ +3). I understand that 17:15 is the UTC time but I don't understand, how did zinc get 20:15 because I'm not in +3 TZ.

**How to reproduce the issue?**
Insert some record to it and see.

**What version of ZincSearch are you using?**
public.ecr.aws/zinclabs/zinc:latest
Version 0.3.5
CommitHash e9bd2126489f3f8317ff4f466176f4b811792ced
BuildDate 2022-11-08T16:07:31Z

**Anything else that you can tell that will help us diagnose and resolve the issue efficiently?**

**Any attachments/screenshots?**
https://imgur.com/a/e5mycnV

**Which service(s) is this relate to?**
This could be GUI or API

**Comment by hengfeiyang** [comment]
Maybe this can help you https://docs.zincsearch.com/api/index/update-mapping/#custom-timestamp-field

**Comment by gaby** [comment]
@hengfeiyang Are the docs are now pointing to ZincObserve, any way to fix that?

**Comment by hengfeiyang** [comment]
@gaby thanks, updated.
