### ISSUE TITLE
SDK support

### ISSUE THREAD

**Issue by hengfeiyang** [zincsearch/zincsearch#708]
- [x] Go https://github.com/zinclabs/sdk-go-zincsearch
- [x] Python https://github.com/zinclabs/sdk-python-zincsearch
- [x] NodeJS https://github.com/zinclabs/sdk-nodejs-zincsearch
- [ ] Java

**Comment by alexander-schranz** [comment]
Would like to have a official SDK for PHP :)

Currently working on a [search engine abstraction](https://github.com/schranz-search/schranz-search) where I would also like to support Zinc.

**Comment by hengfeiyang** [comment]
@alexander-schranz Which version of PHP do you use?

**Comment by alexander-schranz** [comment]
@hengfeiyang 8.1 / 8.2

**Comment by alexander-schranz** [comment]
@hengfeiyang feel free to ping me is there is something I can try out.

**Comment by alexander-schranz** [comment]
I see you are using openai generator to create SDKs. Is there any plan yet for PHP SDK? would really like to test it out :)

**Comment by prabhatsharma** [comment]
No plans for PHP SDK for now.

**Comment by zhaoli2315** [comment]
who has sdk for java

**Comment by hengfeiyang** [comment]
@zhaoli2315 you can use elasticsearch java sdk.
