### ISSUE TITLE
Subscription 

### ISSUE THREAD

**Issue by gedw99** [zincsearch/zincsearch#745]
I was wondering if there is a way to do subscriptions ? 

Set a query and get a notification ( or similar ) when the query result changes . 

I doubt zinc is designed for this but I figured it’s worth asking :) 

of course can always poll and compare results . Maybe there is caching and / or hashing of query result to make pollling not so terrible in terms of perf ..

**Comment by hengfeiyang** [comment]
Ha, there is no this feature, maybe like you said, we should get the query and make a sign, and query it with an interval.
