### ISSUE TITLE
Create index need http PUT method, but the document describe is POST method

### ISSUE THREAD

**Issue by lijunwyf21** [zincsearch/zincsearch#852]
**Which service(s) is this relate to?**
This could be  API

Create index need http PUT method, but the document describe is POST method

**Comment by lemoba** [comment]
> **Which service(s) is this relate to?** This could be API
> 
> Create index need http PUT method, but the document describe is POST method

POST is to create an index and PUT is to update an index, but both POST and PUT are able to create when the index does not exist. If the index already exists then you will receive an error message when you create it again with POST

**Comment by hengfeiyang** [comment]
We also updated the documents https://zincsearch-docs.zinc.dev/api/index/create/
