### ISSUE TITLE
Playground offline

### ISSUE THREAD

**Issue by Niek** [zincsearch/zincsearch#855]
Just FYI, the linked domain https://playground.dev.zincsearch.com/ does not exist:

```bash
$ ping playground.dev.zincsearch.com
ping: cannot resolve playground.dev.zincsearch.com: Unknown host
```

**Comment by gaby** [comment]
I was just removed from the README, so i'm guessing it will stay offline.

**Comment by prabhatsharma** [comment]
Yes, we will not be hosting it anymore. We will let folks try it out themselves. Takes less than 2 minutes on their laptop.
