### ISSUE TITLE
ZINC_MAX_RESULTS The default value is inconsistent with the description in the comments.

### ISSUE THREAD

**Issue by cnn007** [zincsearch/zincsearch#871]
![image](https://user-images.githubusercontent.com/13449400/234588398-2958bad3-0a86-47cb-8ac2-b12128c95773.png)

**Comment by cnn007** [comment]
ok https://github.com/zincsearch/zincsearch-docs/pull/20

**Comment by hengfeiyang** [comment]
updated: https://zincsearch-docs.zinc.dev/environment-variables/
