### ISSUE TITLE
自定义词典文件设置后好像没用

### ISSUE THREAD

**Issue by yunxb** [zincsearch/zincsearch#872]
两个问题
1、部分文本字段不希望被全文索引应该如何设置呢
2、自定义词典问题
我设置了ZINC_PLUGIN_GSE_DICT_PATH 自定义词典路径环境变量，相对路径绝对路径都试过，重启了zincsearch，但是搜索不到，正确设置词典路径应该是咋样的？![]![20230428205508](https://user-images.githubusercontent.com/45444779/235155682-4140a328-b5db-4e8f-a8f7-ee826d1fb959.png)

![20230428211710](https://user-images.githubusercontent.com/45444779/235158701-07fa39eb-f92e-4a27-8a2e-860a7b4536ca.png)

**Comment by hengfeiyang** [comment]
Please refer https://mp.weixin.qq.com/s/g9fcKNSEHqwiK8Tt3MY3GA
