### ISSUE TITLE
Issue with bucketing in Text fields

### ISSUE THREAD

**Issue by dinbabs** [zincsearch/zincsearch#874]
**What were you trying to achieve?**
Get distinct values out my data using Bucketing aggregation for text and number field

**What action did you take?**
Had 2 fields in my data 1)text and 2)Number

Used the below query
```
{
    "search_type": "matchall",
    "from": 0,
    "max_results": 0,
    "aggs": {
        "text": {
            "agg_type": "term",
            "field": "text_test"
        },
        "number": {
            "agg_type": "term",
            "field": "num_test"
        }
    }
}
```

**What action/response/output did you expect?**
I expected bucketing on both number and text field as mentioned in the documentation
https://zincsearch-docs.zinc.dev/api/search/aggregation/

**What actually happened?**
Bucketing returned only for number field but for text field it didnot work, just got the total count back

```
"aggregations": {
	"text": {
            "buckets": [
                {
                    "doc_count": 4,
                    "key": 0,
                    "key_as_string": ""
                }
            ]
        }
        "number": {
            "buckets": [
                {
                    "doc_count": 2,
                    "key": 123,
                    "key_as_string": "123"
                },
                {
                    "doc_count": 2,
                    "key": 321,
                    "key_as_string": "321"
                }
            ]
        }
        
    }
```

**How to reproduce the issue?**

**What version of ZincSearch are you using?**
v0.4.5

**Anything else that you can tell that will help us diagnose and resolve the issue efficiently?**
Sample data I used for test
```
{
    "text_test": "test1",
    "num_test" : 321
}

{
    "text_test": "test2",
    "num_test" : 123
}

{
    "text_test": "test1",
    "num_test" : 123
}

{
    "text_test": "test2",
    "num_test" : 321
}
```
**Any attachments/screenshots?**

**Which service(s) is this relate to?**
Issue in both Zincsearch API and Elasticsearch compatible API

**Comment by hengfeiyang** [comment]
text field doesn't support aggregation. because it split to many tokens, can't be aggregation.

if you want aggregation distinct, you can use keyword type or enable keyword for text.

refer: https://zincsearch-docs.zinc.dev/environment-variables/

```
ZINC_ENABLE_TEXT_KEYWORD_MAPPING=true
```

Then you can use aggregation on the field `text_test.keyword`

**Comment by dinbabs** [comment]
keyword type solved the issue 
Thanks a lot @hengfeiyang !
