### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by gedw99** [zincsearch/zincsearch#877]
I need to feed data about images and videos into zinc.

the parser would be “ outside “ of zinc and then feed the data into zinc I guess.

What’s the recommended way to “plugin” to zinc.

**Comment by gedw99** [comment]
Mhh seems the ingestion area of the way to go ?

https://zincsearch-docs.zinc.dev/ingestion/filebeat/

filebeats is written in golang so seems easy .

**Comment by gedw99** [comment]
Or single record over http 

https://zincsearch-docs.zinc.dev/ingestion/single-record/

Jump in with recommendations if you feel like it

**Comment by prabhatsharma** [comment]
Yeah, you could use single records. but bulk is faster.
