### ISSUE TITLE
zincsearch is using a lot of CPU, how should I optimize it?

### ISSUE THREAD

**Issue by brookxs** [zincsearch/zincsearch#878]
My server has a 32-core CPU, but zincsearch's occupancy rate is over 1000%.
Is there anything I can do to optimize it? I'm using the default configuration.

 PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                      
19509 root      20   0   21.6g   4.9g 695208 S  1317 15.6 384:52.35 zincsearch

**Comment by brookxs** [comment]
We have 17 index files and the number of slices is 3, about 200m documents. The version of zincsearch used is 0.4.5

**Comment by hengfeiyang** [comment]
What's your index map and query case, let's check if something can improve.

**Comment by jcleng** [comment]
@hengfeiyang When logging is if the same key data type is inconsistent will be an exception, and then I added a random key as the key, but the amount of data up will lead to cpu is very high, there is a best practice?

```php
// one api data
'content' => [
    'datatime' => '1723709022',
],
// other api data
'content' => [
    'datatime' => '2024-08-15 16:03:42',
],

// them use requestid for key
'content' => [
    $requestid => $datatime, // 1723709022 and 2024-08-15 16:03:42
],
```
