### ISSUE TITLE
/es/{index}/_search There may be problems with pagination

### ISSUE THREAD

**Issue by RayFongChan** [zincsearch/zincsearch#885]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**What were you trying to achieve?**

pagination

**What action did you take?**

/es/{index}/_search

**What action/response/output did you expect?**

When there is no data on the last page, no data is displayed, but now the data of the penultimate page is displayed

**What actually happened?**

There are 11 pieces of data in zincsearch, I pass from15, size5, why can I still find out the data, the found data seems to have the same effect as from6, size5

**What version of ZincSearch are you using?**

0.4.5

**Comment by parselife** [comment]
I had met this too, According to the doc, I think  `es page` is not supported yet.

**Comment by hengfeiyang** [comment]
thanks report, will fix

**Comment by hengfeiyang** [comment]
@RayFongChan Can you try to restart ZincSearch, and check again? i can't reproduce this issue.

**Comment by RayFongChan** [comment]
![image](https://github.com/zincsearch/zincsearch/assets/35999171/c1f70e2c-c995-4433-af17-955c67226c68)
![image](https://github.com/zincsearch/zincsearch/assets/35999171/7737fb10-7c6b-4675-a87b-50a59ff246db)
Thanks Reply, There are a total of 37 pieces of data, the subscript starts from 40, and 10 pieces of data are queried. The desired effect is that there is no data, but now there will be 10 pieces of data displayed. Or is there something wrong with my    operation?
@hengfeiyang 
params:
{"query":{"bool":{"must":[{"match":{"state":{"query":1}}},{"match":{"is_public":{"query":1}}}]}},"sort":[{"click_nums":"desc"},{"create_time":"desc"}],"from":40,"size":10}
result:
{"took":0,"timed_out":false,"_shards":{"total":12,"successful":12,"skipped":0,"failed":0},"hits":{"total":{"value":37},"max_score":0.8408486818342437,"hits":[{"_index":"congding_office","_type":"_doc","_id":"29","_score":0.07910125180875428,"@timestamp":"2023-06-05T03:28:08.54324352Z","_source":{"@timestamp":"2023-06-05T03:28:08.54324352Z","category_id":"[1, 4, 7, 10]","click_nums":2,"create_time":1683269880,"id":29,"is_public":1,"name":"就是一个ppt","state":1,"type":3}},{"_index":"congding_office","_type":"_doc","_id":"18","_score":0.5600653096784693,"@timestamp":"2023-06-05T03:28:08.511513344Z","_source":{"@timestamp":"2023-06-05T03:28:08.511513344Z","category_id":"[1, 4, 7, 10]","click_nums":2,"create_time":1683269880,"id":18,"is_public":1,"name":"就是一个ppt","state":1,"type":3}},{"_index":"congding_office","_type":"_doc","_id":"16","_score":0.41908579681308766,"@timestamp":"2023-06-05T03:28:08.511481856Z","_source":{"@timestamp":"2023-06-05T03:28:08.511481856Z","category_id":"[1, 4, 7, 10]","click_nums":2,"create_time":1683269880,"id":16,"is_public":1,"name":"就是一个ppt","state":1,"type":3}},{"_index":"congding_office","_type":"_doc","_id":"20","_score":0.716779418512973,"@timestamp":"2023-06-05T03:28:08.51154432Z","_source":{"@timestamp":"2023-06-05T03:28:08.51154432Z","category_id":"[1, 4, 7, 10]","click_nums":2,"create_time":1683269880,"id":20,"is_public":1,"name":"就是一个ppt","state":1,"type":3}},{"_index":"congding_office","_type":"_doc","_id":"28","_score":0.8408486818342437,"@timestamp":"2023-06-05T03:28:08.543230208Z","_source":{"@timestamp":"2023-06-05T03:28:08.543230208Z","category_id":"[1, 4, 7, 10]","click_nums":2,"create_time":1683269880,"id":28,"is_public":1,"name":"就是一个ppt","state":1,"type":3}},{"_index":"congding_office","_type":"_doc","_id":"15","_score":0.8408486818342437,"@timestamp":"2023-06-05T03:28:08.511465216Z","_source":{"@timestamp":"2023-06-05T03:28:08.511465216Z","category_id":"[1, 4, 7, 10]","click_nums":2,"create_time":1683269880,"id":15,"is_public":1,"name":"就是一个ppt","state":1,"type":3}},{"_index":"congding_office","_type":"_doc","_id":"1","_score":0.39431843986578324,"@timestamp":"2023-06-05T03:28:08.475792128Z","_source":{"@timestamp":"2023-06-05T03:28:08.475792128Z","category_id":"[1, 4, 7, 10]","click_nums":190,"create_time":1683268332,"id":1,"is_public":1,"name":"培训机构发展计划","state":1,"type":1}},{"_index":"congding_office","_type":"_doc","_id":"2","_score":0.41908579681308766,"@timestamp":"2023-06-05T03:28:08.475912448Z","_source":{"@timestamp":"2023-06-05T03:28:08.475912448Z","category_id":"[3, 28, 32, 38]","click_nums":16,"create_time":1683269880,"id":2,"is_public":1,"name":"就是一个ppt","state":1,"type":3}},{"_index":"congding_office","_type":"_doc","_id":"45","_score":0.12139217511320236,"@timestamp":"2023-06-05T03:28:08.60639744Z","_source":{"@timestamp":"2023-06-05T03:28:08.60639744Z","category_id":"[2, 16, 19, 22]","click_nums":1,"create_time":1685863771,"id":45,"is_public":1,"name":"工作簿1","state":1,"type":2}},{"_index":"congding_office","_type":"_doc","_id":"42","_score":0.12139217511320236,"@timestamp":"2023-06-05T03:28:08.606336Z","_source":{"@timestamp":"2023-06-05T03:28:08.606336Z","category_id":"[1, 4, 7, 10]","click_nums":1,"create_time":1685862794,"id":42,"is_public":1,"name":"培训机构发展计划 (11)","state":1,"type":1}}]}}

**Comment by hengfeiyang** [comment]
Please try v0.4.6

**Comment by RayFongChan** [comment]
Thanks
