### ISSUE TITLE
package github.com/blugelabs/ice/compress not found

### ISSUE THREAD

**Issue by secoba** [zincsearch/zincsearch#888]
![image](https://github.com/zincsearch/zincsearch/assets/25523634/eaf51477-fd4f-4f39-af5d-b0d448aa73b6)

----

![image](https://github.com/zincsearch/zincsearch/assets/25523634/444b4d5c-fef5-4e8d-9c64-662592dd60d2)

![image](https://github.com/zincsearch/zincsearch/assets/25523634/bd12f964-b291-47fc-bde4-ee7e47574102)

**Comment by hengfeiyang** [comment]
We replaced this library to our own fork:

```
github.com/blugelabs/ice => github.com/zincsearch/ice v1.1.3
```
