### ISSUE TITLE
How to use zincsearch as a embedded library

### ISSUE THREAD

**Issue by kcmvp** [zincsearch/zincsearch#889]
Note: Any feature request that do not follow below template will be closed without consideration. You may remove this line while filing a feature request.

**Is your feature request related to a problem? Please describe.**
I want to use **zincsearch** as a library and don't want to the search WebUI. 

**Describe the solution you'd like**
I want to use **zincsearch** as a library and don't want to the search WebUI. 

**Describe alternatives you've considered**

so I want to remove all the other dependencies except for the **core part**
**Additional context**

**Comment by hengfeiyang** [comment]
You can consider using https://github.com/blugelabs/bluge

**Comment by gedw99** [comment]
@kcmvp 

anpther way is to just edit the line that embeds the web gui

then no web gui in the binary, if that’s what you want.

then compile
