### ISSUE TITLE
search_after vs from for pagination

### ISSUE THREAD

**Issue by andrewarrow** [zincsearch/zincsearch#941]
This style:

```
   "from": 0, 
   "max_results": 20,
```

seems to work fine but:

```
"search_after": ["id123"]
```

always gives me the first page of results.

"Using search_after can be more efficient for deep pagination compared to using from and max_results, especially when dealing with large result sets. Avoid counting and skipping a large number of documents."

Does zinc not handle `search_after`?

**Comment by hengfeiyang** [comment]
we haven't support `search_after`

**Comment by andrewarrow** [comment]
i see. No problem. Maybe I'll fork and add that if I really need it. BTW Zinc is awesome. Using it in production and so much better than a JVM.

**Comment by hengfeiyang** [comment]
If you can add it and contribute it back, that is will be great
