### ISSUE TITLE
Is there a difference between the zinc original api and es compatible api?

### ISSUE THREAD

**Issue by liuxinbin12138** [zincsearch/zincsearch#948]
When I send a request with es api (such as 127.0.0.1:4080/es/gse2/_search), the wanted results are returned, but when I use its original api (such as 127.0.0.1:4080/api/gse2/_search), many unrelated texts are recalled and all their scores are 1.0
--------------------------------------------------------------
An example:
{
    "took": 0,
    "timed_out": false,
    "_shards": {
        "total": 3,
        "successful": 3,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 5
        },
        "max_score": 1,
        "hits": [
            {
                "_index": "gse2",
                "_type": "_doc",
                "_id": "258UXAxWBF0",
                "_score": 1,
                "@timestamp": "2024-01-19T06:30:39.530207232Z",
                "_source": {
                    "@timestamp": "2024-01-19T06:30:39.530207232Z",
                    "text": "对于大多数安全相关的汽车应用，因果链的数据传播往往有一些端到端实时性约束来遵守汽车安全性准则ISO 26262。此外，此外，当今的汽车系统高度分布并且它们通常运行在分布式架构上，这种架构包括多个由标准总线连接而成的电子控制单元(ECU)。"
                }
            },
            {
                "_index": "gse2",
                "_type": "_doc",
                "_id": "258UXACcABW",
                "_score": 1,
                "@timestamp": "2024-01-19T06:30:39.545147136Z",
                "_source": {
                    "@timestamp": "2024-01-19T06:30:39.545147136Z",
                    "text": "因此，为分布式系统的因果链提供一个高效的端到端的时序分析策略是非常重要的，使得复杂汽车系统的严格的端到端实时需求可以高效地验证。"
                }
            },
            {
                "_index": "gse2",
                "_type": "_doc",
                "_id": "258UXAsgD3G",
                "_score": 1,
                "@timestamp": "2024-01-19T06:30:39.51454336Z",
                "_source": {
                    "@timestamp": "2024-01-19T06:30:39.51454336Z",
                    "text": "汽车系统通常遵循一些关于因果链数据最大生存时间的严格的约束。本文中，我们提出了一种高效的用于分析因果链最大数据生存时间的方法。特别地，我们将计算因果链最大数据生存时间上界问题转化为计算因果链中连续的Last-to-Last数据传播实例的释放间隔上界问题。"
                }
            },
            {
                "_index": "gse2",
                "_type": "_doc",
                "_id": "258UXAxWBEY",
                "_score": 1,
                "@timestamp": "2024-01-19T06:30:39.515437056Z",
                "_source": {
                    "@timestamp": "2024-01-19T06:30:39.515437056Z",
                    "text": "由于问题的转化，我们能够在多项式时间复杂度下快速地得到一个相当准确的数据生存时间的上界。实验证明了我们的方法可以在较低的计算代价下得到很高的分析精度。"
                }
            },
            {
                "_index": "gse2",
                "_type": "_doc",
                "_id": "258UXAxWBEZ",
                "_score": 1,
                "@timestamp": "2024-01-19T06:30:39.515437056Z",
                "_source": {
                    "@timestamp": "2024-01-19T06:30:39.515437056Z",
                    "text": "随着人工智能技术的快速发展，汽车系统中包含了越来越多有数据依赖的组件通过端到端的计算来实现智能驾驶。由于系统的复杂性，汽车系统通常被建模成许多因果链来描述有数据依赖的任务的逻辑顺序（如感知、处理与决策）。"
                }
            }
        ]
    }
}

**Comment by andrewarrow** [comment]
i ended up using only the ES compatible part of zinc. How many people are using the api or both?

**Comment by liuxinbin12138** [comment]
> i ended up using only the ES compatible part of zinc. How many people are using the api or both?

I want to use "gse" analyzer to support Chinses advanced, but when I use its original api, the returned data are strange, but using ES api it works.
