### ISSUE TITLE
query for missing or must_not exists

### ISSUE THREAD

**Issue by andrewarrow** [zincsearch/zincsearch#950]
I tried both:

```
{
  "query": {
    "missing": {
      "field": "your_field_name"
    }
  }
}
```

or

```
{
  "query": {
    "bool": {
      "must_not": {
        "exists": {
          "field": "your_field_name"
        }
      }
    }
  }
}
```

but can't get it to return just the documents that do not yet having a value for a newly added your_field_name.

**Comment by KaniuBillows** [comment]
https://github.com/zincsearch/zincsearch/blob/f8b1436487807b107659d6f444a52c9fa442d3c0/pkg/uquery/query/exists.go#L24C1-L26C2

Here you can see: Zincsearch doesn't support exists query. And the deeper reason is that bluge does not provide relevant APIs.

**Comment by andrewarrow** [comment]
ah thank u
