### ISSUE TITLE
Panic with nil pointer dereference

### ISSUE THREAD

**Issue by KaniuBillows** [zincsearch/zincsearch#954]
Note: Any issue that does not follow below template will be closed without consideration. You may remove this line when filing issue.

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**What were you trying to achieve?**

**What action did you take?**

**What action/response/output did you expect?**

**What actually happened?**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa42dc1]

goroutine 37519 [running]:
github.com/blugelabs/bluge/index.(*Writer).executeMergeTask(0xc015f02d80, 0xc0221d7b60, 0xc02215cc00)
	/root/go/pkg/mod/github.com/seafileltd/bluge@v1.0.1/index/merge.go:208 +0x621
github.com/blugelabs/bluge/index.(*Writer).planMergeAtSnapshot(0xc015f02d80, 0x0?, 0xc01968c500, {0xa, 0xf4240, 0x4024000000000000, 0xa, 0x7d0, 0x4000000000000000, 0x0, ...})
	/root/go/pkg/mod/github.com/seafileltd/bluge@v1.0.1/index/merge.go:118 +0x2db
github.com/blugelabs/bluge/index.(*Writer).mergerLoop(0xc015f02d80, 0x0?, 0xc0221bd920)
	/root/go/pkg/mod/github.com/seafileltd/bluge@v1.0.1/index/merge.go:56 +0x31f
created by github.com/blugelabs/bluge/index.OpenWriter in goroutine 37450
	/root/go/pkg/mod/github.com/seafileltd/bluge@v1.0.1/index/writer.go:131 +0x7df
```

**How to reproduce the issue?**
Sry, there may be not a accurate reproduction method, I just create and delete multiple times through bulk.
**What version of ZincSearch are you using?**
latest
**Anything else that you can tell that will help us diagnose and resolve the issue efficiently?**
This may be an error caused by merging segments, under certain branch conditions, no new segment is generated, (or it is skipped), and then trying to close the empty segment pointer
**Any attachments/screenshots?**

**Which service(s) is this relate to?**
This could be GUI or API

**Comment by hengfeiyang** [comment]
@KaniuBillows it looks you forked something that is not our build version. can you try our build version, if it still report this error?
