### ISSUE TITLE
How to close pprof endpoint?

### ISSUE THREAD

**Issue by feiyangbeyond** [zincsearch/zincsearch#960]
I deploy zincsearch on my esc though docker.

http://<ip>:4080/debug/pprof is valid.

How to close the endpoint?

**Comment by feiyangbeyond** [comment]
What I mean is to make the /debug/pprof endpoint invalid and not accessible directly

**Comment by KaniuBillows** [comment]
That's a Golang debug tool, in zincsearch, it depends on the environment variable `GIN_MODE`,  you can set the value to `release`, and it will disable go pprof.
