### ISSUE TITLE
data not visible in webui, but can retrieve via api

### ISSUE THREAD

**Issue by creativeson** [zincsearch/zincsearch#963]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

I deploy zincsearch on my mac though brew.

**What action/response/output did you expect?**
I can see the new data in the web UI immediately after inserting it, but it disappears after a while. However, when I check the data via the API, it still exists. The data just doesn't show up in the web UI.

**What version of ZincSearch are you using?**
0.4.10
**Anything else that you can tell that will help us diagnose and resolve the issue efficiently?**

**Any attachments/screenshots?**
<img width="1446" alt="截圖 2024-05-31 下午3 40 02" src="https://github.com/zincsearch/zincsearch/assets/100126727/9f02e6c3-2db1-474b-8e54-aa2dd3408da7">

<img width="1042" alt="截圖 2024-05-31 下午3 35 51" src="https://github.com/zincsearch/zincsearch/assets/100126727/00bf69d6-0645-46d5-95b7-07c7439bc4a5">

**Which service(s) is this relate to?**
This could be GUI

**Comment by KaniuBillows** [comment]
maybe you need to mark the checkbox on your left screen, like `_source`. 
And notice that your search in the webUI contains a timestamp filter (default 30 mins), you may need to change it on your webUI.

**Comment by zzstarfish** [comment]
exactly! I met the same issue and wondered whether it is  bug. Then I found this thread and realized it is the timestamp filter on the right above corner!  Just change the filter (e.g. changed it to 6 months, so that you can see the data created in these 6 months.) and suddently all the data appeared! 
The webUI works great! It is really convinient!
