### ISSUE TITLE
 err expected { character for map value

### ISSUE THREAD

**Issue by djklim87** [zincsearch/zincsearch#979]
**What were you trying to achieve?**

Ingest data

**What action did you take?**

```
curl "${ZINC_SEARCH_HOST}/es/_index_template" -X POST --data-binary @./template.json
curl "${ZINC_SEARCH_HOST}/api/_bulk" -X POST --data-binary ./logs10m_splitted.txt
```

**What action/response/output did you expect?**

```
{"message":"bulk data inserted","record_count":1}
```

**What actually happened?**

I got 
```
{"message":"bulk data inserted","record_count":0}
```
With error in logs
```
{"level":"error","time":"2024-10-09T11:24:21Z","message":"bulk.json.Unmarshal: ./data/logs10m_splitted.txt, err expected { character for map value"}
2024-10-09T11:24:21.083744506Z {"level":"info","method":"POST","code":200,"took":2,"time":"2024-10-09T11:24:21Z","message":"/api/_bulk"}
```

But JSON is correct

**How to reproduce the issue?**

```
curl "${ZINC_SEARCH_HOST}/es/_index_template" -X POST --data-binary @./template.json
curl "${ZINC_SEARCH_HOST}/api/_bulk" -X POST --data-binary ./logs10m_splitted.txt
```

**What version of ZincSearch are you using?**
`Zinc 0.4.10`

**Anything else that you can tell that will help us diagnose and resolve the issue efficiently?**

**Any attachments/screenshots?**
[template.json](https://github.com/user-attachments/files/17307220/template.json)
[logs10m_splitted.txt](https://github.com/user-attachments/files/17307249/logs10m_splitted.txt)

**Which service(s) is this relate to?**
API

**Comment by hengfeiyang** [comment]
You need use `@` for file. change it:
```
curl "${ZINC_SEARCH_HOST}/es/_index_template" -X POST --data-binary @./template.json
curl "${ZINC_SEARCH_HOST}/api/_bulk" -X POST --data-binary ./logs10m_splitted.txt
```
to this:
```
curl "${ZINC_SEARCH_HOST}/es/_index_template" -X POST --data-binary @./template.json
curl "${ZINC_SEARCH_HOST}/api/_bulk" -X POST --data-binary @./logs10m_splitted.txt
```

**Comment by djklim87** [comment]
Yes my fault
